-- 코드를 입력하세요
WITH RECURSIVE EMPTY_HOUR_TABLE AS (
    SELECT 0 AS HOUR, 0 AS COUNT
    UNION
    SELECT HOUR + 1, COUNT
    FROM EMPTY_HOUR_TABLE
    WHERE HOUR < 23
)

SELECT UT.HOUR HOUR, SUM(UT.COUNT) COUNT
FROM (
    SELECT ET.HOUR HOUR, ET.COUNT COUNT
    FROM EMPTY_HOUR_TABLE AS ET
    UNION ALL
    SELECT HOUR(AO.DATETIME) HOUR, COUNT(ANIMAL_ID) COUNT
    FROM ANIMAL_OUTS AS AO
    GROUP BY HOUR
    ORDER BY HOUR
) AS UT
GROUP BY HOUR
ORDER BY HOUR