-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM MEMBER_PROFILE a, REST_REVIEW b 
WHERE  a.MEMBER_ID = b.MEMBER_ID AND a.MEMBER_ID = (SELECT MEMBER_ID FROM REST_REVIEW
                    GROUP BY MEMBER_ID 
                    ORDER BY COUNT(REVIEW_ID) desc limit 1)

ORDER BY REVIEW_DATE
