-- 코드를 입력하세요
SELECT a.PRODUCT_ID, a.PRODUCT_NAME, SUM(b.AMOUNT * a.PRICE)TOTAL_SALES
FROM FOOD_PRODUCT a
JOIN FOOD_ORDER b on a.PRODUCT_ID = b.PRODUCT_ID
WHERE b.PRODUCE_DATE between '2022-05-01' and '2022-05-31'
GROUP BY b.PRODUCT_ID
ORDER BY TOTAL_SALES desc , PRODUCT_ID