-- 코드를 입력하세요
SELECT c.APNT_NO, a.PT_NAME, a.PT_NO, c.MCDP_CD, b.DR_NAME, c.APNT_YMD
FROM PATIENT a 
JOIN APPOINTMENT c on a.PT_NO = c.PT_NO
JOIN DOCTOR b on b.DR_ID = c.MDDR_ID
WHERE APNT_YMD like '%2022-04-13%'
AND c.APNT_CNCL_YN = 'N' AND c.MCDP_CD = 'CS'
ORDER BY APNT_YMD