-- 코드를 입력하세요
SELECT DISTINCT a.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR a
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY b on a.CAR_ID = b.CAR_ID
WHERE a.CAR_TYPE = '세단' and b.START_DATE between '2022-10-01' and '2022-10-31'
ORDER BY CAR_ID desc

