-- 코드를 입력하세요
SELECT a.REST_ID, a.REST_NAME, a.FOOD_TYPE, a.FAVORITES, a.ADDRESS, 
ROUND(AVG(REVIEW_SCORE),2) SCORE
FROM REST_INFO a
JOIN REST_REVIEW b on a.REST_ID = b.REST_ID
WHERE ADDRESS like '서울%'
GROUP BY REST_ID
HAVING SCORE IS NOT NULL
ORDER BY SCORE desc , FAVORITES desc
